CREATE TABLE IF NOT EXISTS public.courses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    title TEXT NOT NULL,
    initials TEXT NOT NULL,
    link TEXT NULL,

    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_initials_unique UNIQUE (initials)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.notes (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    course_initials TEXT NULL,
    profile_id UUID NULL,
    content TEXT NOT NULL,

    CONSTRAINT notes_pkey PRIMARY KEY (id),
    CONSTRAINT notes_course_initials_fkey FOREIGN KEY (course_initials) REFERENCES public.courses (initials) ON DELETE SET NULL,
    CONSTRAINT notes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles (id) ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.admins (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    user_email TEXT NOT NULL,

    CONSTRAINT admins_pkey PRIMARY KEY (id),
    CONSTRAINT admins_user_email_fkey FOREIGN KEY (user_email) REFERENCES auth.users (email) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    username TEXT NOT NULL,

    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_email_fkey FOREIGN KEY (user_email) REFERENCES auth.users (email) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.questions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    profile_id UUID NULL,
    content TEXT NOT NULL,
    course_initials TEXT NOT NULL,

    CONSTRAINT questions_pkey PRIMARY KEY (id),
    CONSTRAINT questions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles (id) ON DELETE SET NULL,
    CONSTRAINT questions_course_initials_fkey FOREIGN KEY (course_initials) REFERENCES public.courses (initials) ON DELETE CASCADE
) TABLESPACE pg_default;
